### ISSUE TITLE
Operational mismatch between the paper and the given code. 

### ISSUE THREAD

**Issue by BardOfCodes** [kevin-kaixu/grass_pytorch#2]
For example: 
The Encoder in the given code repository:
 ```
class AdjEncoder(nn.Module):

    def __init__(self, feature_size, hidden_size):
        super(AdjEncoder, self).__init__()
        self.left = nn.Linear(feature_size, hidden_size)
        self.right = nn.Linear(feature_size, hidden_size, bias=False)
        self.second = nn.Linear(hidden_size, feature_size)
        self.tanh = nn.Tanh()

    def forward(self, left_input, right_input):
        output = self.left(left_input)
        output += self.right(right_input)
        output = self.tanh(output)
        output = self.second(output)
        output = self.tanh(output)
        return output
```
This set of instructions imply that to find the encoding of the parent:
1) Both the children are first processed independently.
2) The **summation** of these two children is then processed for getting the parent feature.

This is quite different from the procedure outlined in the paper: 
![image](https://user-images.githubusercontent.com/3109345/45550384-4c2d6680-b848-11e8-9fca-45a9303af199.png)

Where basically,
1) Both the children are concatenated into one vector.
2) A Linear Layer of size **2L** then takes the concatenated vector as input, and outputs the parent feature.

Although in a end-to-end training, the formulation in this repository may also work, the procedure in the paper seems more intuitive.

To the best of my knowledge, this seems to be a flaw. It would be useful to know the reasons for the formulation used in this repository.

**Comment by junli-lj** [comment]
So I think
![image](https://user-images.githubusercontent.com/27905751/45552846-c7047a80-b864-11e8-82f3-cf5e250d6fa2.png)

and W_ae can also be implemented as multi-layers for better performance.

**Comment by BardOfCodes** [comment]
Yes that makes sense. 

I was thinking of it the weight matrix to be of `2n x 2n` rather than `2n x n`. With `2n x 2n` we would be missing out on half the relations if we implement it in terms of  2 weight matrix of `n x n`. 
But as you pointed out, its rather a relation `2n x n`, and hence it can be written separately without any issue. 

Thanks for pointing this out @junli-lj !
