### ISSUE TITLE
python trian.py wrong, No module named 'pytorch_tools'

### ISSUE THREAD

**Issue by hamkido** [kevin-kaixu/grass_pytorch#4]
I installed pytorchfold via readme.md and used python setup.py. When I try to use train.py, these characters are displayed on my terminal. I tried to fix it but failed

Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from torchfoldext import FoldExt
  File "/home/hamki/what/nerual-net/grass_pytorch/torchfoldext.py", line 1, in <module>
    from pytorch_tools import torchfold
ModuleNotFoundError: No module named 'pytorch_tools'

The following is my operating environment:

operating system: linux
miniconda: python3.7 pytorch pytorch.vision etc.

Details:
|  Name |        Version |       Build  Channel |
 | --------   | -----:   | :----: |
| asn1crypto |    0.24.0 |       py37_0   |
| blas |          1.0 | mkl   |
| ca-certificates           | 2019.1.23 |         0   |
| certifi |       2019.3.9 |     py37_0   |
| cffi |          1.11.5     |      py37he75722e_1   |
| chardet |       3.0.4 |        py37_1   |
| conda |         4.6.11 |       py37_0   |
| conda-env |     2.6.0 | 1   |
| cryptography |2.4.2 |py37h1ba5d50_0   |
| cudatoolkit |   10.0.130 |          0   |
| cycler |        0.10.0 |       py37_0   |
| dbus |          1.13.6 |   h746ee38_0   |
| expat |         2.2.6 |    he6710b0_0   |
| fontconfig |    2.13.0 |   h9420a91_0   |
| freetype |      2.9.1 |    h8a8886c_1   |
| glib |          2.56.2 |   hd408876_0   |
| gst-plugins-base    |      1.14.0 |   hbbd80ab_1   |
| gstreamer |     1.14.0 |   hb453b48_1   |
| icu |           58.2 |     h9c2bf20_1   |
| idna |          2.8 |          py37_0   |
| intel-openmp |  2019.3 |          199   |
| jpeg |          9b |       h024ee3a_2   |
| kiwisolver |    1.0.1 |py37hf484d3e_0   |
| libedit |       3.1.20170329       |  h6b74fdf_2   |
| libffi |        3.2.1 |    hd88cf55_4   |
| libgcc-ng |     8.2.0 |    hdf63c60_1   |
| libgfortran-ng |7.3.0 |    hdf63c60_0   |
| libpng |        1.6.36 |   hbc83047_0   |
| libstdcxx-ng |  8.2.0 |    hdf63c60_1   |
| libtiff |       4.0.10 |   h2733197_2   |
| libuuid |       1.0.3 |    h1bed415_2   |
| libxcb |        1.13 |     h1bed415_1   |
| libxml2 |       2.9.9 |    he19cac6_0   |
| matplotlib |    3.0.3 |py37h5429711_0   |
| mkl |           2019.3 |          199   |
| mkl_fft |       1.0.10        |   py37ha843d7b_0   |
| mkl_random |    1.0.2 |py37hd81dba3_0   |
| ncurses |       6.1 |      he6710b0_1   |
| ninja |         1.9.0 |py37hfd86e86_0   |
| numpy |         1.16.2      |     py37h7e9f1db_0   |
| numpy-base |    1.16.2       |    py37hde5b4d6_0   |
| olefile |       0.46 |         py37_0   |
| openssl |       1.1.1b |   h7b6447c_1   |
| pcre |          8.43 |     he6710b0_0   |
| pillow |        5.4.1 |py37h34e0f95_0   |
| pip |           18.1 |         py37_0   |
| pycosat |       0.6.3 |py37h14c3975_0   |
| pycparser |     2.19 |         py37_0   |
| pyopenssl |     18.0.0 |       py37_0   |
| pyparsing |     2.3.1 |        py37_0   |
| pyqt |          5.9.2 |py37h05f1152_2   |
| pysocks |       1.6.8 |        py37_0   |
| python |        3.7.1 |    h0371630_7   |
| python-dateutil        |   2.8.0 |        py37_0   |
| pytorch |       1.0.1         |  py3.7_cuda10.0.130_cudnn7.4.2_2   pytorch |
| pytz |          2018.9 |       py37_0   |
| qt |5.9.7 |    h5867ecd_1   |
| readline |      7.0 |      h7b6447c_5   |
| requests |      2.21.0 |       py37_0   |
| ruamel_yaml |   0.15.46       |   py37h14c3975_0   |
| setuptools |    40.6.3 |       py37_0   |
| sip |           4.19.8       |   py37hf484d3e_0   |
| six |           1.12.0 |       py37_0   |
| sqlite |        3.26.0 |   h7b6447c_0   |
| tk |8.6.8 |    hbc83047_0   |
| torchfold |     0.1.0 |        pypi_0    pypi |
| torchvision |   0.2.2 |          py_3    pytorch |
| tornado |       6.0.2 |py37h7b6447c_0   |
| urllib3 |       1.24.1 |       py37_0   |
| wheel |         0.32.3 |       py37_0   |
| xz |5.2.4 |    h14c3975_4   |
| yaml |          0.1.7 |    had09818_2   |
| zlib |          1.2.11 |   h7b6447c_3   |
| zstd |          1.3.7 |    h0b5b093_0   |

**Comment by hansongfang** [comment]
Try the following. It works for me. 

run "pip install torchfold"

Edit the following 
from pytorch_tools import torchfold -> import torchfold
from pytorch_tools.torchfold import Fold -> from torchfold import Fold

**Comment by ruili3** [comment]
> Try the following. It works for me.
> 
> run "pip install torchfold"
> 
> Edit the following
> from pytorch_tools import torchfold -> import torchfold
> from pytorch_tools.torchfold import Fold -> from torchfold import Fold

Did you receive any other mistake in running this code? I did the same as you to avoid the error, after this I received an error "IndexError: dimension specified as 0 but tensor has no dimensions" in this code. How do you handle this issue? Thanks a lot!

**Comment by kevin-kaixu** [comment]
> 
> 
> > Try the following. It works for me.
> > run "pip install torchfold"
> > Edit the following
> > from pytorch_tools import torchfold -> import torchfold
> > from pytorch_tools.torchfold import Fold -> from torchfold import Fold
> 
> Did you receive any other mistake in running this code? I did the same as you to avoid the error, after this I received an error "IndexError: dimension specified as 0 but tensor has no dimensions" in this code. How do you handle this issue? Thanks a lot!

I guess it is caused by the update of pytorch-tools.
Would you like to check with the earlier version of pytorch-tools before October, 2017?

**Comment by hamkido** [comment]
I am sorry. Some changes have taken place in my life.  I no longer continue
to study artificial intelligence, and I have not solved this problem at the
time.

**Comment by ruili3** [comment]
I changed the pytorch-tools version to 0.0.1, but still encountered same promlems. So I change the pytorch version to 0.2.0 and python to 3.5, which is close to your configuration according to the implementation time. And now it works. 
Thanks a lot!
